spring:
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # AdminUserController en auth-service (@RequestMapping /users)
        - id: auth-service-users
          uri: lb://auth-service
          predicates:
            - Path=/users/**

        - id: org-service
          uri: lb://org-service
          predicates:
            - Path=/org/**

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/documents/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
