spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5434/db_opsflow?currentSchema=msc_document
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: msc_document
        hbm2ddl.create_namespaces: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

app:
  jwt:
    secret: =======================OpsFlowSecretKey2025BySeniorDev======================
  storage:
    location: uploads
  rabbitmq:
    exchange: document-exchange
    routing-key:
      created: document.created
      updated: document.updated

storage:
  r2:
    enabled: ${R2_ENABLED:false}
    endpoint: ${R2_ENDPOINT:https://ce59a4a791a9ca8a248b7ab7769dbc8a.r2.cloudflarestorage.com}
    region: ${R2_REGION:auto}
    bucket: ${R2_BUCKET:}
    access-key-id: ${R2_ACCESS_KEY_ID:}
    secret-access-key: ${R2_SECRET_ACCESS_KEY:}
    public-base-url: ${R2_PUBLIC_BASE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
